### PR TITLE
update README, fix few things in config and requirements

### PR DESCRIPTION
**Pull request by dimpase**

### CODE REVIEW

**Comment by dimpase** [comment]
README now says how to build (on Unix), and it now builds on Linux and macOS.

On Linux everything passes, on macOS some pytest errors.

**Comment by dimpase** [comment]
actually, using the latest `numpy` etc, the tests pass on macOS too. One should constrain the version of `numpy` in requirements, I suppose.

**Comment by Martin-Seysen** [comment]
Hello Dima,
It appears that github does not like some kinds of formatting in README.rst. So I had to put a link into the README.
Also, in my Ubuntu version I have to manipulate the enviromnent variables PYTHONPATH and LD_LIBRARY_PATH.
Is the section 'Quick installation and test' in the README now ok for you?
Can you tell me more about the numpy rquirements?

**Comment by dimpase** [comment]
oh, it's .rst, not .md, as GitHub normally does? I haven't noticed, sorry.

**Comment by dimpase** [comment]
On macOS (intel, I don't have acess to Arm) it works for me numpy 1.23.3, but doesn't with 1.20.

**Comment by dimpase** [comment]
PYTHONPATH and LD_LIBRARY_PATH are not needed in a venv.
```shell
cd mmgroup/
python3 -n venv . 
source bin/activate
pip3 install -r requirements.txt
python3 setup.py build_ext --inplace
deactivate # (optional)
```
should just work on any reasonable Unix system and new enough python3 and packages.

**Comment by Martin-Seysen** [comment]
So either my Ubuntu system is not reasonable, or I simply have too little exprience with Linux.
To make the virtual environment work at all, I had to install:
sudo apt install python3.10-venv.

My next question is;
Does the command 'cd mmgroup/' switch to the root directory of your Git clone of the mmgroup repository?
Then I can build the extensions, but  running pytest (inside setup.py or from the shell) fails.
Also, I cannot import the mmgroup package when invoking python3 from the shell.

When using my more primitive approch manipulating the environment variables, everything works fine on my system.

**Comment by dimpase** [comment]
> Does the command 'cd mmgroup/' switch to the root directory of your Git clone of the mmgroup repository?
yes.

Regarding pytest, 
could it be that you need the latest numpy on Ubuntu too?

**Comment by dimpase** [comment]
> Also, I cannot import the mmgroup package when invoking python3 from the shell.

for this to work, you need to remain in the venv, i.e. don't run `deactivate`, or if you did, `source bin/activate` again.

venv is not Unix specific, it's "pure python", see https://docs.python.org/3/library/venv.html

**Pull request merged**
